# Generated by Django 6.0 on 2026-04-20 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='Слаг')),
                ('icon', models.CharField(default='bi-bookmark', help_text='CSS-класс иконки Bootstrap Icons, например «bi-cpu».', max_length=60, verbose_name='Иконка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активное')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Научное направление',
                'verbose_name_plural': 'Научные направления',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(allow_unicode=True, max_length=80, unique=True, verbose_name='Слаг')),
                ('icon', models.CharField(default='bi-calendar2-event', help_text='CSS-класс иконки Bootstrap Icons.', max_length=60, verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активное')),
            ],
            options={
                'verbose_name': 'Тип мероприятия',
                'verbose_name_plural': 'Типы мероприятий',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='Слаг')),
                ('short_description', models.CharField(blank=True, help_text='Показывается в карточке в каталоге (до 500 символов).', max_length=500, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('event_format', models.CharField(choices=[('offline', 'Очно'), ('online', 'Дистанционно'), ('hybrid', 'Гибридный')], default='offline', max_length=20, verbose_name='Формат')),
                ('starts_at', models.DateTimeField(verbose_name='Начало')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('location', models.CharField(blank=True, help_text='Адрес или название аудитории для очных форматов.', max_length=255, verbose_name='Место проведения')),
                ('online_url', models.URLField(blank=True, help_text='Используется для дистанционного и гибридного формата.', verbose_name='Ссылка на трансляцию')),
                ('seats_total', models.PositiveIntegerField(default=0, help_text='0 — без ограничения по количеству участников.', verbose_name='Всего мест')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='events/covers/%Y/%m/', verbose_name='Обложка')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='draft', max_length=20, verbose_name='Статус')),
                ('is_featured', models.BooleanField(default=False, help_text='Показывается на главной странице.', verbose_name='Рекомендуемое')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='catalog.direction', verbose_name='Научное направление')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='catalog.eventtype', verbose_name='Тип мероприятия')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('cancelled', 'Отменена'), ('waitlist', 'Лист ожидания'), ('attended', 'Посетил(а)')], default='pending', max_length=20, verbose_name='Статус')),
                ('note', models.TextField(blank=True, help_text='Дополнительная информация от участника (опционально).', verbose_name='Комментарий участника')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='catalog.event', verbose_name='Мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Регистрация на мероприятие',
                'verbose_name_plural': 'Регистрации на мероприятия',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'status'], name='catalog_eve_event_i_6123f7_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'user'), name='unique_event_user_registration')],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-starts_at'], name='catalog_eve_starts__4e9af6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', '-starts_at'], name='catalog_eve_status_0caf37_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_format'], name='catalog_eve_event_f_364985_idx'),
        ),
    ]
