# Generated by Django 6.0 on 2026-04-21 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_seed_sample_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventregistration',
            name='unique_event_user_registration',
        ),
        migrations.AddField(
            model_name='event',
            name='allow_waitlist',
            field=models.BooleanField(default=True, help_text='Если мест нет, новые заявки попадают в лист ожидания.', verbose_name='Разрешить лист ожидания'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_closes_at',
            field=models.DateTimeField(blank=True, help_text='Если не заполнено, заявки принимаются до момента начала мероприятия.', null=True, verbose_name='Окончание приёма заявок'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_opens_at',
            field=models.DateTimeField(blank=True, help_text='Если не заполнено, заявки принимаются сразу после публикации мероприятия.', null=True, verbose_name='Старт приёма заявок'),
        ),
        migrations.AddField(
            model_name='event',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Новые заявки получают статус «Ожидает подтверждения» и подтверждаются куратором вручную.', verbose_name='Требуется подтверждение куратора'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отменено'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, help_text='Пользователь, отменивший заявку (участник или куратор).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Кем отменена'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Подтверждено'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='email',
            field=models.EmailField(blank=True, help_text='Контактный email, указанный в заявке.', max_length=254, verbose_name='Email для связи'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='full_name',
            field=models.CharField(blank=True, help_text='Снимок ФИО на момент подачи заявки.', max_length=255, verbose_name='ФИО участника'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='organization',
            field=models.CharField(blank=True, max_length=255, verbose_name='Организация / подразделение'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность / статус'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='source',
            field=models.CharField(choices=[('self', 'Самостоятельно'), ('curator', 'Добавлен куратором'), ('import', 'Импорт')], default='self', max_length=20, verbose_name='Источник заявки'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='waitlist_position',
            field=models.PositiveIntegerField(blank=True, help_text='Заполняется автоматически при постановке заявки в лист ожидания. Меньшее значение — ближе к подтверждению.', null=True, verbose_name='Позиция в листе ожидания'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('waitlist', 'Лист ожидания'), ('cancelled', 'Отменена'), ('attended', 'Посетил(а)'), ('no_show', 'Не явился')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['user', 'status'], name='catalog_eve_user_id_4cffe7_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', 'waitlist_position'], name='catalog_eve_event_i_5aee9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed', 'waitlist'])), fields=('event', 'user'), name='unique_active_event_user_registration'),
        ),
    ]
