# Generated by Django 6.0 on 2026-04-22 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_eventregistration_unique_event_user_registration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='Слаг')),
                ('description', models.CharField(blank=True, help_text='Необязательная подсказка для пользователя при выборе темы.', max_length=255, verbose_name='Краткое описание')),
                ('icon', models.CharField(default='bi-chat-dots', help_text='CSS-класс иконки Bootstrap Icons.', max_length=60, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=100, help_text='Темы с меньшим значением отображаются выше.', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Тема обращения',
                'verbose_name_plural': 'Темы обращений',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EventReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='Как подписать отзыв. Снимок на момент отправки.', max_length=255, verbose_name='Имя автора')),
                ('author_email', models.EmailField(blank=True, help_text='Необязательно для анонимных отзывов.', max_length=254, verbose_name='Email автора')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 — очень плохо'), (2, '2 — плохо'), (3, '3 — нормально'), (4, '4 — хорошо'), (5, '5 — отлично')], help_text='Оценка мероприятия по шкале от 1 до 5.', verbose_name='Оценка')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(help_text='Впечатления от мероприятия.', verbose_name='Текст отзыва')),
                ('pros', models.TextField(blank=True, help_text='Что особенно понравилось (опционально).', verbose_name='Плюсы')),
                ('cons', models.TextField(blank=True, help_text='Что стоит улучшить (опционально).', verbose_name='Минусы')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('published', 'Опубликован'), ('rejected', 'Отклонён'), ('hidden', 'Скрыт')], default='pending', max_length=20, verbose_name='Статус модерации')),
                ('moderation_note', models.TextField(blank=True, help_text='Причина отклонения или внутренние заметки.', verbose_name='Комментарий модератора')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Проверено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.event', verbose_name='Мероприятие')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_event_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Кто проверил')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор (если авторизован)')),
            ],
            options={
                'verbose_name': 'Отзыв о мероприятии',
                'verbose_name_plural': 'Отзывы о мероприятиях',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'status', '-created_at'], name='catalog_eve_event_i_d08b1d_idx'), models.Index(fields=['status', '-created_at'], name='catalog_eve_status_c61edf_idx'), models.Index(fields=['user', '-created_at'], name='catalog_eve_user_id_89b089_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeedbackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Как к вам обращаться.', max_length=255, verbose_name='Имя / ФИО')),
                ('email', models.EmailField(help_text='Электронная почта, на которую придёт ответ.', max_length=254, verbose_name='Email для ответа')),
                ('phone', models.CharField(blank=True, help_text='Необязательный контактный телефон.', max_length=32, verbose_name='Телефон')),
                ('organization', models.CharField(blank=True, help_text='Необязательно: место работы или учёбы.', max_length=255, verbose_name='Организация')),
                ('subject', models.CharField(blank=True, help_text='Краткий заголовок обращения.', max_length=255, verbose_name='Тема сообщения')),
                ('message', models.TextField(help_text='Текст обращения.', verbose_name='Сообщение')),
                ('consent_to_processing', models.BooleanField(default=False, help_text='Отмечается пользователем при отправке формы.', verbose_name='Согласие на обработку персональных данных')),
                ('subscribe_to_news', models.BooleanField(default=False, help_text='Пользователь согласен получать новостную рассылку.', verbose_name='Подписаться на новости')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP отправителя для анти-спам проверок и аудита.', null=True, verbose_name='IP-адрес')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('referer', models.URLField(blank=True, help_text='Страница, с которой была отправлена форма.', max_length=500, verbose_name='Реферер')),
                ('source', models.CharField(choices=[('contact_form', 'Форма обратной связи'), ('event_page', 'Страница мероприятия'), ('footer', 'Подвал сайта'), ('other', 'Другое')], default='contact_form', max_length=30, verbose_name='Источник')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('answered', 'Отвечено'), ('closed', 'Закрыто'), ('spam', 'Спам')], default='new', max_length=20, verbose_name='Статус')),
                ('admin_note', models.TextField(blank=True, help_text='Заметки администраторов, не видны пользователю.', verbose_name='Внутренний комментарий')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('answer_text', models.TextField(blank=True, help_text='Итоговый ответ пользователю (опционально сохраняется для истории).', verbose_name='Текст ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_feedback_messages', to=settings.AUTH_USER_MODEL, verbose_name='Кто ответил')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Сотрудник, которому поручено обработать обращение.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_feedback_messages', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('related_event', models.ForeignKey(blank=True, help_text='Заполняется, если обращение касается конкретного мероприятия.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_messages', to='catalog.event', verbose_name='Связанное мероприятие')),
                ('user', models.ForeignKey(blank=True, help_text='Ссылка на учётную запись, если сообщение оставил авторизованный пользователь. Для анонимных обращений — пусто.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор (если авторизован)')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='catalog.feedbacktopic', verbose_name='Тема обращения')),
            ],
            options={
                'verbose_name': 'Обращение обратной связи',
                'verbose_name_plural': 'Обращения обратной связи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='catalog_fee_created_06c3a0_idx'), models.Index(fields=['status', '-created_at'], name='catalog_fee_status_a686a0_idx'), models.Index(fields=['email'], name='catalog_fee_email_00a90d_idx'), models.Index(fields=['user', '-created_at'], name='catalog_fee_user_id_b129ba_idx')],
            },
        ),
    ]
