# Generated by Django 5.2.2 on 2026-04-26 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_eventbookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmessage',
            name='attachment',
            field=models.FileField(blank=True, help_text='Необязательно: PDF, документ, изображение или архив.', null=True, upload_to='feedback/attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'odt', 'txt', 'rtf', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'zip'])], verbose_name='Вложение'),
        ),
    ]
