# Generated by Django 5.2.2 on 2026-05-14 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_feedbackmessage_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistrationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('waitlist', 'Лист ожидания'), ('cancelled', 'Отменена'), ('attended', 'Посетил(а)'), ('no_show', 'Не явился')], max_length=20, verbose_name='Предыдущий статус')),
                ('new_status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('waitlist', 'Лист ожидания'), ('cancelled', 'Отменена'), ('attended', 'Посетил(а)'), ('no_show', 'Не явился')], max_length=20, verbose_name='Новый статус')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время изменения')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_registration_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='catalog.eventregistration', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'История статуса заявки',
                'verbose_name_plural': 'История статусов заявок',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['registration', '-changed_at'], name='catalog_eve_registr_e35c2a_idx'), models.Index(fields=['changed_by', '-changed_at'], name='catalog_eve_changed_db5991_idx')],
            },
        ),
    ]
